New Blog Post on 2025-01-29 21:57:25

diff --git a/sync_n_start b/sync_n_start
--- a/sync_n_start
+++ b/sync_n_start
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 echo "Start syncing from obsidian vault. . ."
-rsync -av --delete "/srv/dev-disk-by-uuid-5d9f109b-e277-4117-973e-c7e67e8422ab/super_vault/yson/Obsidian Super Vault/posts/" "/home/yson-server/myblog/content/posts/"
+rsync -av --delete "/srv/dev-disk-by-uuid-5d9f109b-e277-4117-973e-c7e67e8422ab/super_vault/yson/Obsidian Super Vault/posts/" "/home/yson-server/projects/myblog/content/posts/"
 
 echo "Processing image links in Markdown files..."
 if [ ! -f "image_sync.py" ]; then
@@ -9,5 +9,11 @@ if [ ! -f "image_sync.py" ]; then
     exit 1
 fi
 
+if ! python3 image_sync.py; then
+    echo "Failed to process image links."
+    exit 1
+fi
+
 echo "Starting up website. . ."
 hugo server --bind 0.0.0.0 --baseURL http://10.179.5.96:1313/   
+
